### ISSUE TITLE
Is it possible to run it as non root?

### ISSUE THREAD

**Issue by smartaquarius10** [kubernetes-sigs/custom-metrics-apiserver#107]
Hello,

While setting runasNonRoot true, it throws an error. It is expecting to run as root.

By any chance is it possible to run it as non root because security is concern in production and bypassing policy is not possible.

Kind Regards
Tanul

**Comment by olivierlemasle** [comment]
Hi @smartaquarius10 

This depends on how you build the container image for your adapter.

The image for the "test-adapter" created with `make test-adapter-container` uses `scratch` as its base image, and runs as `root`.
But if you replace `scratch` by e.g. `gcr.io/distroless/static:nonroot` in: https://github.com/kubernetes-sigs/custom-metrics-apiserver/blob/ec8119c3676e72bcffb8b973451048d1cdee3f68/Makefile#L51

then you'll be able to use `runasNonRoot: true`.

**Comment by smartaquarius10** [comment]
@olivierlemasle, I've specified -` --cert-dir=/tmp` as an argument to `/adapter` command in yaml file. Is that ok to use like this.

**Comment by olivierlemasle** [comment]
Yes, I would either:

- use a base image ready for non-root, such as `gcr.io/distroless/static:nonroot`
- or use any image, such as `gcr.io/distroless/static:latest`, `scatch` or `alpine:latest`, and add `--cert-dir=/tmp` because `apiserver.local.config/certificates` is not writable.

(However, I would advise you to use a [Distroless](https://github.com/GoogleContainerTools/distroless) or `scratch` image, rather than `alpine`, in order to limit the surface of attack.)

**Comment by smartaquarius10** [comment]
@olivierlemasle, Actually, my controller code is merged in the same code base as custom metrics server. I forgot dividing them in two separate containers and now its monolithic. If I use this image does any problem occur in custom controller packages provided by kubernetes team like controller-runtime etc. I think I need to do the impact analysis of that. 

I will separate them in my upcoming sprints.

**Comment by olivierlemasle** [comment]
Hi @smartaquarius10,

In #135, we've added `--cert-dir` to the manifest for test-adapter.

I'll close this issue. Feel free to re-open it if your question is not really solved.

/assign
/close
