### ISSUE TITLE
Can we start adding tags that correspond their matching K8s release?

### ISSUE THREAD

**Issue by dprotaso** [kubernetes-sigs/custom-metrics-apiserver#67]
Knative makes use of this cusom-metrics-apiserver. We also try to pin our K8s dependencies & other components to specific K8s versions because of the [version skew policy](https://kubernetes.io/docs/setup/release/version-skew-policy/).

We're not able to do that with this metrics server repo since there aren't any tags and branches. It currently involves visiting the repo and skimming through the `go.mod` across commits.

I was hoping this repo (at a minimum) could have branches for each k8s minor release similar [kube-openapi repo](https://github.com/kubernetes/kube-openapi/branches).

ie. release-1.17, release-1.18, release-1.19 etc.

**Comment by dprotaso** [comment]
as an FYI - here's the script I wrote to bump our k8s related deps

https://github.com/knative/serving/blob/a1de2b9fa410c921d2e3cfa5a703f7a9d82ed46e/hack/update-k8s-deps.sh#L53-L55

**Comment by s-urbaniak** [comment]
cc @dgrisonnet maybe this is something we can work on together.

**Comment by dgrisonnet** [comment]
sgtm, let me know whenever you want to start this effort.

**Comment by dgrisonnet** [comment]
Sorry for the long awaited update on this issue @dprotaso.

My plan is to have the major and minor versions of custom-metrics-apiserver in sync with upstream kubernetes and the patch version will be reserved for changes in custom-metrics-apiserver. Some projects such as [cri-o](https://github.com/cri-o/cri-o) already follow this process.

Since we want to be in sync with upstream kubernetes, we should also follow their policy and cut releases for the three most recent minor releases (1.21, 1.20, 1.19). For each of them my plan is to cut the release based on the commit that updated the minor version of the kubernetes dependencies and tag it. Minor releases of the project will then be tied to the kubernetes dependencies minor version updates.

cc @dprotaso @s-urbaniak @serathius @kawych

**Comment by dgrisonnet** [comment]
Closing since we added a release process and released:
- https://github.com/kubernetes-sigs/custom-metrics-apiserver/releases/tag/v1.19.0
- https://github.com/kubernetes-sigs/custom-metrics-apiserver/releases/tag/v1.20.0
- https://github.com/kubernetes-sigs/custom-metrics-apiserver/releases/tag/v1.21.0
